notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker-compose pull

script:
  - docker-compose run emscripten
  - make test