notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:1.39.2-fastcomp bash

script:
  - docker exec -it emscripten make
  - make test